/* tslint:disable */
/* eslint-disable */
/**
 * EPYC API
 * epyc API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FrameImageData,
    FrameImageDataFromJSON,
    FrameImageDataFromJSONTyped,
    FrameImageDataToJSON,
} from './';

/**
 * 
 * @export
 * @interface FramePlayData
 */
export interface FramePlayData {
    /**
     * 
     * @type {string}
     * @memberof FramePlayData
     */
    title?: string;
    /**
     * 
     * @type {FrameImageData}
     * @memberof FramePlayData
     */
    image?: FrameImageData;
}

export function FramePlayDataFromJSON(json: any): FramePlayData {
    return FramePlayDataFromJSONTyped(json, false);
}

export function FramePlayDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): FramePlayData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': !exists(json, 'title') ? undefined : json['title'],
        'image': !exists(json, 'image') ? undefined : FrameImageDataFromJSON(json['image']),
    };
}

export function FramePlayDataToJSON(value?: FramePlayData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'image': FrameImageDataToJSON(value.image),
    };
}


