/* tslint:disable */
/* eslint-disable */
/**
 * EPYC API
 * epyc API
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Avatar
 */
export interface Avatar {
    /**
     * 
     * @type {string}
     * @memberof Avatar
     */
    url: string;
    /**
     * 
     * @type {number}
     * @memberof Avatar
     */
    width: number;
    /**
     * 
     * @type {number}
     * @memberof Avatar
     */
    height: number;
}

export function AvatarFromJSON(json: any): Avatar {
    return AvatarFromJSONTyped(json, false);
}

export function AvatarFromJSONTyped(json: any, ignoreDiscriminator: boolean): Avatar {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'url': json['url'],
        'width': json['width'],
        'height': json['height'],
    };
}

export function AvatarToJSON(value?: Avatar | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'url': value.url,
        'width': value.width,
        'height': value.height,
    };
}


