name: Deploy Server

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '16.8.x' # set this to the node version to use
  AWS_APP_NAME: 'epyc'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        shell: bash
        run: npm install

      - name: Build Server
        shell: bash
        run: |
          npm test
          npm run server-build

      - name: Build Client
        shell: bash
        run: |
          npm run client-build

      - name: Package
        shell: bash
        run: |
          npm prune --production
          zip -r ./${{env.AWS_APP_NAME}}.zip . -x ".github/*" ".vscode/*" "api/*" "client/*" "server/*" "/.git*" "/.prettier*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Upload to S3
        run: |
          aws deploy push --application-name ${{ env.AWS_APP_NAME }} --s3-location s3://phlegmatic-deploy/${{env.AWS_APP_NAME}}.zip

      - name: Deploy to EC2
        run: |
          aws deploy create-deployment --application-name ${{ env.AWS_APP_NAME }} --s3-location bucket=phlegmatic-deploy,key=${{ env.AWS_APP_NAME }}.zip,bundleType=zip --deployment-group-name ${{ env.AWS_APP_NAME }} --ignore-application-stop-failures
