name: PR Test Build

on: pull_request

env:
  NODE_VERSION: '14.x' # set this to the node version to use

jobs:
  build-and-deploy:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Build Server
        shell: bash
        run: |
          cd server
          npm install
          npm test
          npm run build

      - name: Build Client
        shell: bash
        run: |
          cd client
          npm install
          npm run build
